CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255),
  password VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL
);

CREATE TABLE dapil (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL
);

CREATE TABLE kecamatan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(255),
  dapil_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (dapil_id) REFERENCES dapil(id)
);

CREATE TABLE kelurahan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(255),
  kecamatan_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (kecamatan_id) REFERENCES kecamatan(id)
);

CREATE TABLE tps (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(255),
  kelurahan_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (kelurahan_id) REFERENCES kelurahan(id)
);

CREATE TABLE caleg (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(255),
  dapil_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (dapil_id) REFERENCES dapil(id)
);

CREATE TABLE jumlah_suara (
  id INT AUTO_INCREMENT PRIMARY KEY,
  jumlah INT,
  dapil_id INT,
  kecamatan_id INT,
  kelurahan_id INT,
  tps_id INT,
  caleg_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (dapil_id) REFERENCES dapil(id),
  FOREIGN KEY (kecamatan_id) REFERENCES kecamatan(id),
  FOREIGN KEY (kelurahan_id) REFERENCES kelurahan(id),
  FOREIGN KEY (tps_id) REFERENCES tps(id),
  FOREIGN KEY (caleg_id) REFERENCES caleg(id)
);

CREATE TABLE bukti_suara (
  id INT AUTO_INCREMENT PRIMARY KEY ,
  foto LONGBLOB,
  keterangan VARCHAR(255),
  jumlah_suara_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (jumlah_suara_id) REFERENCES jumlah_suara(id)
);

